### ISSUE TITLE
Support for SkinnedMeshRenderer?

### ISSUE THREAD

**Issue by f0ff886f** [chrisnolet/QuickOutline#1]
Would this work with SkinnedMeshRenderers? It doesn't seem to support it out of the box, but if you can point me in the right direction I could take a look at adding it.

**Comment by son1cman** [comment]
> Would this work with SkinnedMeshRenderers? It doesn't seem to support it out of the box, but if you can point me in the right direction I could take a look at adding it.

Check unity asset store, theres an update for skinnedmeshrenders, Have you solve the overlapping issue this have? Can you please send me the tweaks you have to make and shader to make work per object.

**Comment by jul-ya** [comment]
Did anyone of you fix the multimaterial/submesh problem? I'd really need this and there's nothing new on here...

**Comment by dustingraham** [comment]
> Did anyone of you fix the multimaterial/submesh problem? I'd really need this and there's nothing new on here...

Just came here because I ran into this problem. Shucks. Only the last material seems to be included in the outline.

**Comment by chrisnolet** [comment]
Thank you for your questions!

1. Skinned mesh renderers are now supported.
2. There is a version of Quick Outline that supports overlapping objects: [`feature/per-object`](https://github.com/chrisnolet/QuickOutline/tree/feature/per-object).
3. The latest version also works for objects with multiple submeshes.

Thank you, again, for your time and feedback!
