### ISSUE TITLE
Unity pauses when the outline.cs is added runtime on a big mesh

### ISSUE THREAD

**Issue by salvolannister** [chrisnolet/QuickOutline#11]
I tryed to had in runtime outline.cs to a gameobject on a mesh with 53581 verts and unity completely pause.
I managed to avoid this issue running line 96 of the _**Awake**_ function in a Task 

`Task t = Task.Run ( () =>  LoadSmoothNormals()); `

but then the object it s outlined just in part ( from certain sides it is not visible) .

Do you know how can I solve this issue (if I can) ?

**Comment by chrisnolet** [comment]
Thanks for your feedback! Load-time performance has been significantly improved with the latest version. (It's still synchronous, but it is a lot more performant.) Thank you, again!

**Comment by chrisnolet** [comment]
Thanks for your feedback! Load-time performance has been significantly improved with the latest version. (It's still synchronous, but it is a lot more performant.)
