### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by ilijastevanovic** [chrisnolet/QuickOutline#14]
Soon after adding this to my project, I noticed more and more memory being allocated in the editor after every play, until it got to Unity taking 10GB of RAM even when not in Play Mode.

Seems that adding this code to `OnDestroy` fixes the problem:

```C#
foreach (var meshFilter in GetComponentsInChildren<MeshFilter>()) {
        if (meshFilter.sharedMesh.subMeshCount > 1)
        {
            meshFilter.sharedMesh.subMeshCount = meshFilter.sharedMesh.subMeshCount - 1;
        }
}
```

A submesh was being added to the `sharedMesh` in every `Awake()`, but was never being removed.

**Comment by chrisnolet** [comment]
Thank you! The latest update has official support for multiple submeshes included, and works around the memory leak introduced by some of the community patches.
