### ISSUE TITLE
Sometimes there are a lot of GC Alloc in Awake

### ISSUE THREAD

**Issue by corle-bell** [chrisnolet/QuickOutline#19]
![QQ图片20210903100914](https://user-images.githubusercontent.com/7886480/131940287-34d2ea7d-f9ae-416f-bbc0-26b76273f39d.png)

**Comment by corle-bell** [comment]
i found the way to sovle it, do not use mesh.normals in the loop.  mesh normals will make GC Alloc.

**Comment by chrisnolet** [comment]
Thank you for your note, and later pull request. This performance bug has been fixed in the latest release. Thank you, again!
