### ISSUE TITLE
Overlapping objects

### ISSUE THREAD

**Issue by son1cman** [chrisnolet/QuickOutline#2]
When i use this for 2 cube for example, if one cube overlap each other, then outline of overlap area gone, can i modify shader to fix this? I want outline show up by Z order, then if 1 cube have bigger order, it will show its outline instead of don't show anything like bellow images. Thanks!

**Comment by DanielDarko** [comment]
Sorry to bump this but did you find a solution? Having similar problems and can't find an answer that works.

**Comment by PicoPlanetDev** [comment]
@DanielDarko Have you figured this out by change? I am now struggling with the same issue.

**Comment by andbloom** [comment]
Has anybody found a solution yet?

**Comment by PicoPlanetDev** [comment]
@andbloom Not really, however, I'd be willing to share with you the outline shader I used in replacement. It works pretty well, its just one of those that you need to round the normals at sharp corners.

**Comment by andbloom** [comment]
@PicoPlanetDev That'd be amazing, thank you!

**Comment by PicoPlanetDev** [comment]
Will send it tomorrow morning when I am back at my computer!

**Comment by PicoPlanetDev** [comment]
@andbloom Take this code and put it into a shader named Outline.shader https://gist.github.com/PicoPlanetDev/c16de20a6aba3013eae99d96d9eebe7d
Then create a material using that shader with the desired outline options. Then apply two materials to objects that you want an outline on - the base material (can be anything) and the outline material on top of that.

**Comment by andbloom** [comment]
@PicoPlanetDev Thank you, works perfect!

**Comment by coolboi21** [comment]
Im still waiting to find a solution that works. The solution @PicoPlanetDev did not work for me.

**Comment by andbloom** [comment]
@coolboi21 I found that combining this solution and the outline script works really well.

**Comment by chrisnolet** [comment]
Thank you for your interest, and proposals for working around this issue. The official solution can be found at: [`feature/per-object`](https://github.com/chrisnolet/QuickOutline/tree/feature/per-object).
