### ISSUE TITLE
Fills object instead of outline in Android Cardboard VR

### ISSUE THREAD

**Issue by feoff3** [chrisnolet/QuickOutline#4]
Hi and thanks for the great asset!

I am building a VR app and found your asset quite useful. 
But unfortunately when I am building my app for Android VR in latest Unity, and run it on my Android phone, the resulting outline just fills in the whole object instead of outline.

This how the object with outline enabled looks in Unity Player. Both white figure on the right and box with QR code on the left are outlined with (color = white, width = 3)
![quickoutiline_pc](https://user-images.githubusercontent.com/7068534/71537011-b9221e00-291e-11ea-9382-59e789910354.png)

And this what when I build and run in Android VR:
![quickoutline_buggy_vr](https://user-images.githubusercontent.com/7068534/71537027-e79ff900-291e-11ea-8525-ca98453233cd.png)

Notes:
1. The Outline script is added dynamically (when object is close) to the object
2. I also use a small animation, so actually outline width grows dynamically from 0.3f to 3.0f (0.1f is added to the width each frame). Not tested yet how it works without this animation. 

Please let me know if you need more details
Thanks in advance

**Comment by feoff3** [comment]
edit:
the same thing happens if animation is turned off and width is constant 0.3f

**Comment by feoff3** [comment]
the same thing happens with the demo scene. on android vr all of the shapes are not outlined but filled with the solid color.

**Comment by feoff3** [comment]
I played with the shader a bit. 
It turns out like for Android vert() is executed for all points of mesh while in Windows it is executed for edges of mesh only. 
I am not sure but maybe it is related to https://forum.unity.com/threads/z-buffer-ofs-works-on-pc-but-not-on-mobile.576883/

**Comment by feoff3** [comment]
Well, I managed to find a workaround that works at least for VisibleOnly mode.
Simply replace 'Cull Off' to 'Cull Front' in the shader. Then it uses only unseen vertices that are on the unseen part of the edge to draw an outline.

**Comment by chrisnolet** [comment]
Thanks for your feedback, and for working through this issue!

Unfortunately, stencil buffers aren’t available on some older Android devices with GLES 2.0. The workaround you suggested, (replacing `Cull Off` with `Cull Front` in `OutlineFill.shader`) is the next-best solution if you need to support GLES 2.0.

You may see some visual artifacts, depending on your models, with this solution.
