### ISSUE TITLE
Outline on objects that have multiple materials

### ISSUE THREAD

**Issue by salvolannister** [chrisnolet/QuickOutline#6]
When I use this script with an object with two different Uv maps ( two materials)but only one mesh I have this:
![Outline_example](https://user-images.githubusercontent.com/34481854/80866799-09283d00-8c91-11ea-8cc3-01f86c2e443e.PNG)

This is how it looks like in the editor:
![Object in the editor](https://forum.unity.com/attachments/outline-material-png.612103/)
How can I modify the shader to have all the obj outlined?

**Comment by dehv** [comment]
For everyone that stumbles across this, [here](https://answers.unity.com/questions/1725078/quickoutline-the-outline-is-applied-only-in-a-part.html?childToView=1743996#answer-1743996) is the solution to this issue.

**Comment by chrisnolet** [comment]
This functionality is now built into the latest version. Thank you!

(Please note that the solution referenced above, on Unity Answers, has a memory leak when running in the editor.)
